on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build ${{ matrix.service }}
        run: |
          ls
          docker buildx create --use
          docker buildx bake ${{ matrix.service }}
    strategy:
      matrix:
        service: ["test-api"]
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploying
        uses: D3rHase/ssh-command-action@v0.3.1
        with:
          host: ${{secrets.HOST}}
          user: ${{secrets.NAME}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{secrets.PROJECT_FOLDER}};
            git checkout master;
            git pull;
            docker-compose up

          

