name: test
on: [push]
jobs:
  our-first-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - uses: actions/setup-python@v1
          with:
            python-version: '3.13'
            architecture: 'x64'
        - name: Install requiments
          run: pip install -r requirments.txt
        - name: Run tests
          run: coverage run tests.py
        - name: Tests report
          run: coverage report